### PR TITLE
[FIX] The iOS app example crashes in case of wrong values for a beacon location dictionary

### PR DESCRIPTION
**Pull request by fabiomassimo**
## Summary

The app crashed when registering Eddystone to a new beacon without providing valid Beacon Location latitude and or longitude

## Why

"If the app ain't happy, no body is happy."
Before using a beacon location info dictionary a convenience method is used to fill in all missing requirements 

## Example

In the implementation of `BeaconInfoTableViewCell`

```objective-c
NSDictionary *beaconLocation = [self normalizedBeaconLocationFromBeaconLocationInfo:beaconLocation];
```

### CODE REVIEW

**Comment by marcwan** [comment]
Hi Fabio! Thanks for the bug report. Hadn't run into that one!

Two things:

1. Can you please follow the instructions in [CONTRIBUTING.md](https://github.com/google/beacon-platform/blob/master/CONTRIBUTING.md) at the top of this repo (basically, it confirms you give us permission to redistribute code you contribute to the project).

2. Can you update your code to follow the coding guidelines that this app is using — we're using the [public objective-c guidelines](http://google.github.io/styleguide/objcguide.xml) here.

As for the patch, the real problem is that I expected there to always be a place or a lat/lon — however, that's a bad assumption, so … the correct fix is:

In _BeaconInfoTableViewCell.m_, in `setBeaconLocation:`, change the if to be the following:

    if (beaconLocation[@"placeId"]) {
      // leave this code the same.
    } else if beaconLocation[@"latLng"]) {
      // use the code from the current "else ..."
    } else {
      NSMutableAttributedString *text = [[NSMutableAttributedString alloc] initWithString:@""];
      [text appendAttributedString:[self makeTextMediumBold:@"Location: "]];
      [text appendAttributedString:[[NSAttributedString alloc] initWithString:@"(not specified)"]];
      _beaconLatLngLabel.attributedText = text;

      // Just set the location to somewhere known instead of (0,0) which is in the Atlantic somewhere.
      [self setMapViewToLatitude:37.4814 longitude:-122.0880];
    }

Thanks again for taking the time to help out! Appreciate it.

**Comment by marcwan** [comment]
Hrm … Are you seeing the problem at all that the values in the incoming dictionary aren't "latitude" and "longitude"? Are there other values being set there?  That would require a slightly separate fix ^_^

**Comment by fabiomassimo** [comment]
Thanks for your time to review this. Love what is coming out from Eddystone project.

Unfortunately I don't think I see your last point.
The incoming dictionary contains different values besides latitude and longitude indeed but what causes the crash is a missing assignment for those keys which could be fixed by fallback on default values.

Am I missing something that couldn't make this a proper fix for current issue?

**Comment by marcwan** [comment]
Oh wow, sorry — So are you saying you are, in `setBeaconLocation:`, getting a _non-nil_ `NSDictionary`, but it doesn't contain `"latitude"` and `"longitude"`? Do you know what it _does_ have instead? Yes, I might have lead you the wrong way, sorry ^_^

I actually think your path is 90% correct, but I forgot one line:

in _RegisterBeaconViewController.m_, we'd have to change line 184 to be:

        cell.beaconLocation = @{ @"latLng" : _beaconData[@"latLng"] };

Does that look good to you?

If you look in the Debug console in xcode, you can see the returned JSON for the beacon that's crashing. I'm curious what you see!!

Thanks again, and sorry for the troubles !

**Comment by fabiomassimo** [comment]
I decided to take advantage of CLLocationCoordinate2D struct over the NSNumber explicit casting. This should help us to cover edge case where location coordinate do not have a set value.

What do you think?

**Comment by marcwan** [comment]
Love it — can we fix one last thing: make sure no lines are > 100 chars. Then i'll merge it in. Looks good.

thanks!

**Comment by fabiomassimo** [comment]
Glad to hear!

Thanks for your time and patience.

**Pull request merged**
